import "./globals.css";
import Navbar from "@/components/Navbar";
import { Inter } from "next/font/google";
export const metadata = {
  title: "Kitab hub",
  description: "Generated by create next app",
};
const inter = Inter({ subsets: ["latin"] });
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <>
          <Navbar />
          {children}
        </>
      </body>
    </html>
  );
}
