import "./globals.css";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Kitab hub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <title>
        <link
          href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </title>
      <body>
        <>
          <Navbar />
          {children}
        </>
      </body>
    </html>
  );
}
